####Write confusion matrix in CSV file with following condition1 :
1. Heading and 1st column should be class name
2. The data goes row wise i.e. 1st row will have detail of class1 classified to which classes

In [1]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

evaluation = pd.read_csv("evaluation.csv", header = 0)
evaluation= evaluation.drop(evaluation.columns[0], axis = 1)
classes = list(evaluation.columns)
print(classes)

evaluation = genfromtxt('evaluation.csv', delimiter=',')
print(evaluation)


evaluation = np.delete(evaluation, 0, 0)
evaluation = np.delete(evaluation, 0, 1)
print(evaluation)

conf_matrix = evaluation

['A', 'B', 'C']
[[ nan  nan  nan  nan]
 [ nan  90.   7.   3.]
 [ nan  11. 162.   7.]
 [ nan  14.   8. 118.]]
[[ 90.   7.   3.]
 [ 11. 162.   7.]
 [ 14.   8. 118.]]


In [2]:
i=0
TP = []
TN = []
FP = []
FN = []
Precision_list = []
Recall_list = []
F1_score = []
Accuracy = []
for class_name in classes:
    tp = conf_matrix[i,i]
    TP.append(tp)
    fp = sum(conf_matrix[...,i]) - tp
    FP.append(fp)
    fn = sum(conf_matrix[i]) - tp
    FN.append(fn)
    tn = sum(sum(conf_matrix)) - tp - fp - fn
    TN.append(tn)
    
    precision  = tp / (tp + fp)
    Precision_list.append(precision)
    recall     = tp / (tp + fn)
    Recall_list.append(recall)
    f1_score   = 2*( precision * recall)/(precision + recall)
    F1_score.append(f1_score)
    accuracy   = (tp+tn)/(tp+fn+fp+tn)
    Accuracy.append(accuracy)
    print("TP", tp)
    print("TN", tn)
    print("FP", fp)
    print("FN", fn)

    print('For class', class_name)
    print('\tprecision =', precision)
    print('\trecall =', recall)
    print('\tF1 Score =', f1_score)
    print('\tAccuracy =', accuracy)
    i += 1

print('Micro Avg :')
print('\t For Precision =', sum(TP)/(sum(TP) + sum(FP)))
print('\t For Recall =', sum(TP)/(sum(TP) + sum(FN)))
print('\t For F1 score =', 2*( sum(TP)/(sum(TP) + sum(FP)) * sum(TP)/(sum(TP) + sum(FN)))/(sum(TP)/(sum(TP) + sum(FP)) + sum(TP)/(sum(TP) + sum(FN))))
print('\t For Accuracy = ')

print('Macro Avg :')
print('\t For Precision =', sum(Precision_list)/len(Precision_list))
print('\t For Recall =', sum(Recall_list)/len(Recall_list))
print('\t For F1 score =', sum(F1_score)/len(F1_score))
print('\t For Accuracy = ', sum(Accuracy)/len(Accuracy))

TP 90.0
TN 295.0
FP 25.0
FN 10.0
For class A
	precision = 0.782608695652174
	recall = 0.9
	F1 Score = 0.8372093023255814
	Accuracy = 0.9166666666666666
TP 162.0
TN 225.0
FP 15.0
FN 18.0
For class B
	precision = 0.9152542372881356
	recall = 0.9
	F1 Score = 0.9075630252100839
	Accuracy = 0.9214285714285714
TP 118.0
TN 270.0
FP 10.0
FN 22.0
For class C
	precision = 0.921875
	recall = 0.8428571428571429
	F1 Score = 0.880597014925373
	Accuracy = 0.9238095238095239
Micro Avg :
	 For Precision = 0.8809523809523809
	 For Recall = 0.8809523809523809
	 For F1 score = 0.880952380952381
	 For Accuracy = 
Macro Avg :
	 For Precision = 0.8732459776467699
	 For Recall = 0.8809523809523809
	 For F1 score = 0.8751231141536794
	 For Accuracy =  0.9206349206349206
