In [1]:
import pandas as pd
train_data = pd.read_csv("traindata.csv", header = 0)
test_data = pd.read_csv("testdata.csv", header = 0)

print(train_data)
print(test_data)

     Color  Radius (cm)  Weight (grams) Fruit (class)
0   Yellow          2.3              61         Lemon
1   Yellow          4.8              75         Apple
2    Green          3.6             173          Pear
3   Yellow          2.6              58         Lemon
4   Yellow          2.1              40         Lemon
5    Green          3.0              86         Apple
6   Yellow          3.1              60         Lemon
7   Yellow          5.2             141          Pear
8    Green          2.5              70         Apple
9   Yellow          3.2              79         Apple
10     Red          3.9             101         Apple
11   Green          2.4              62         Lemon
12   Green          4.6             152          Pear
13   Green          4.3             133          Pear
14  Yellow          4.1               0         Lemon
15  Yellow          2.9              53         Lemon
16   Green          4.5             110          Pear
17  Yellow          2.3     

In [2]:
import numpy as np
# drop duplicated rows
train_data = train_data.drop_duplicates()
#print(train_data)
    
# replace zeros entries with np.nan
train_data = train_data.replace(0,np.nan)
train_data = train_data.dropna() # drop all nan entiries 
#print(train_data)

newCols = pd.get_dummies(train_data.iloc[:,0]) 
train_data = pd.concat([newCols, train_data], axis=1) # add them to the transfomed columns to the beggining  of the data frame
train_data = train_data.drop(train_data.columns[3], axis = 1) # drop nominal column (color)   

# drop duplicated rows
test_data= test_data.drop_duplicates()

# transform the nominal feature (color) to dummy
newCols=pd.get_dummies(test_data.iloc[:,0]) 
test_data = pd.concat([newCols, test_data], axis=1) # add them to the transfomed columns to the beggining  of the data frame
test_data= test_data.drop(test_data.columns[3], axis = 1) # drop nominal column (color)  

print("Test Data is", test_data)
print("train data is", train_data)

Test Data is    Green  Red  Yellow  Radius (cm)  Weight (grams)  Predicted (class)  \
0      0    0       1          2.5              64                NaN   
1      1    0       0          4.2              90                NaN   
2      1    0       0          3.2              95                NaN   
3      0    1       0          2.9              65                NaN   
4      0    0       1          2.9              60                NaN   

  Original (class)  
0            Lemon  
1             Pear  
2             Pear  
3            Apple  
4            Lemon  
train data is     Green  Red  Yellow  Radius (cm)  Weight (grams) Fruit (class)
0       0    0       1          2.3            61.0         Lemon
1       0    0       1          4.8            75.0         Apple
2       1    0       0          3.6           173.0          Pear
3       0    0       1          2.6            58.0         Lemon
4       0    0       1          2.1            40.0         Lemon
5       1   

In [3]:
Atrributes_train = list(train_data.columns)
print(Atrributes_train)
classes = train_data[Atrributes_train[-1]]
print(classes)
classes_name = classes.unique()
print(classes_name)

Atrributes_test = list(test_data.columns)
print(Atrributes_test)

['Green', 'Red', 'Yellow', 'Radius (cm)', 'Weight (grams)', 'Fruit (class)']
0     Lemon
1     Apple
2      Pear
3     Lemon
4     Lemon
5     Apple
6     Lemon
7      Pear
8     Apple
9     Apple
10    Apple
11    Lemon
12     Pear
13     Pear
15    Lemon
16     Pear
17    Lemon
18    Apple
19     Pear
20    Lemon
21    Apple
22    Apple
23    Apple
24     Pear
25    Apple
26    Lemon
27    Lemon
28    Lemon
29    Apple
31     Pear
Name: Fruit (class), dtype: object
['Lemon' 'Apple' 'Pear']
['Green', 'Red', 'Yellow', 'Radius (cm)', 'Weight (grams)', 'Predicted (class)', 'Original (class)']


In [4]:
from sklearn import preprocessing

#train data
label_encoder = preprocessing.LabelEncoder()
for attribute in Atrributes_train[:-1] :
    if(train_data[attribute].dtypes == 'object') :
        train_data[attribute]= label_encoder.fit_transform(train_data[attribute]) 
    else :
        normalized_df=(train_data[attribute]-train_data[attribute].min())/(train_data[attribute].max()-train_data[attribute].min())
        train_data[attribute]= normalized_df
    
X_train = train_data[Atrributes_train[:-1]]
#X_train = preprocessing.normalize(X_train)
#X_train['Radius (cm)'] = preprocessing.normalize(X_train['Radius (cm)'])
Y_train = train_data[Atrributes_train[-1]]
print(X_train)
print(Y_train)

#test data
print("test_data")
label_encoder = preprocessing.LabelEncoder()
for attribute in Atrributes_test[:-2] :
    if(test_data[attribute].dtypes == 'object') :
        test_data[attribute]= label_encoder.fit_transform(test_data[attribute])
    else :
        normalized_df=(test_data[attribute]-test_data[attribute].min())/(test_data[attribute].max()-test_data[attribute].min())
        test_data[attribute]= normalized_df
    
X_test = test_data[Atrributes_test[:-2]]
Y_test = test_data[Atrributes_test[-1]]
print(X_test)
print(Y_test)

    Green  Red  Yellow  Radius (cm)  Weight (grams)
0     0.0  0.0     1.0     0.064516        0.157895
1     0.0  0.0     1.0     0.870968        0.263158
2     1.0  0.0     0.0     0.483871        1.000000
3     0.0  0.0     1.0     0.161290        0.135338
4     0.0  0.0     1.0     0.000000        0.000000
5     1.0  0.0     0.0     0.290323        0.345865
6     0.0  0.0     1.0     0.322581        0.150376
7     0.0  0.0     1.0     1.000000        0.759398
8     1.0  0.0     0.0     0.129032        0.225564
9     0.0  0.0     1.0     0.354839        0.293233
10    0.0  1.0     0.0     0.580645        0.458647
11    1.0  0.0     0.0     0.096774        0.165414
12    1.0  0.0     0.0     0.806452        0.842105
13    1.0  0.0     0.0     0.709677        0.699248
15    0.0  0.0     1.0     0.258065        0.097744
16    1.0  0.0     0.0     0.774194        0.526316
17    0.0  0.0     1.0     0.064516        0.150376
18    0.0  1.0     0.0     0.516129        0.458647
19    0.0  0

In [5]:
from sklearn.neighbors import KNeighborsClassifier

for n in range(1,12) :
    print(n)
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train, Y_train)
    y_pred = knn.predict(X_test)
    print(y_pred)


1
['Apple' 'Pear' 'Pear' 'Apple' 'Lemon']
2
['Apple' 'Pear' 'Pear' 'Apple' 'Lemon']
3
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
4
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
5
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
6
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
7
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
8
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
9
['Lemon' 'Pear' 'Pear' 'Lemon' 'Lemon']
10
['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']
11
['Lemon' 'Pear' 'Pear' 'Lemon' 'Lemon']


In [6]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_pred)
print(cm)


[[0 1 0]
 [0 2 0]
 [0 0 2]]


In [7]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

       Apple       0.00      0.00      0.00         1
       Lemon       0.67      1.00      0.80         2
        Pear       1.00      1.00      1.00         2

    accuracy                           0.80         5
   macro avg       0.56      0.67      0.60         5
weighted avg       0.67      0.80      0.72         5

